<a href="https://colab.research.google.com/github/islam-alim/transaction-risk-prediction/blob/main/notebooks/IEEE_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
file_path = "/kaggle/train_transaction.csv"
df = pd.read_csv(file_path, nrows=100_000)
df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Warning: Total number of columns (394) exceeds max_columns (20) limiting to first (20) columns.

In [5]:
df.shape

(16594, 394)

In [15]:
df.columns

Index(['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=394)

In [14]:
df.dtypes

TransactionID       int64
isFraud             int64
TransactionDT       int64
TransactionAmt    float64
ProductCD          object
                   ...
V335              float64
V336              float64
V337              float64
V338              float64
V339              float64
Length: 394, dtype: object

In [16]:
df.isna()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16589,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16590,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
16591,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
16592,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
16593,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [22]:
df.isna().sum().sort_values(ascending=False).head(10)

D7       16214
D13      16103
dist2    15940
D12      15906
D14      15828
D6       15756
D9       14565
D8       14565
V149     13950
V148     13950
dtype: int64

In [23]:
df.isna().mean().mul(100).sort_values(ascending=False).head(10)
# per cent

D7       97.710016
D13      97.041099
dist2    96.058816
D12      95.853923
D14      95.383874
D6       94.949982
D9       87.772689
D8       87.772689
V149     84.066530
V148     84.066530
dtype: float64